time ../bin/cell_move_router ../testcases/case1.txt
time ../bin/cell_move_router ../testcases/case2.txt
time ../bin/cell_move_router ../testcases/case3.txt
time ../bin/cell_move_router ../testcases/case3B.txt
time ../bin/cell_move_router ../testcases/case4.txt
time ../bin/cell_move_router ../testcases/case4B.txt
time ../bin/cell_move_router ../testcases/case5.txt
time ../bin/cell_move_router ../testcases/case5B.txt
time ../bin/cell_move_router ../testcases/case6.txt
time ../bin/cell_move_router ../testcases/case6B.txt